openapi: 3.1.0
info:
  title: EVE Datacore API
  version: 0.0.0
paths:
  /calc/path/{from}/{to}:
    get:
      operationId: GetCalcPathFromTo
      parameters:
        - name: from
          in: path
          required: true
          description: GET /calc/path/:from/:to Parameter
          schema:
            type: number
            format: double
            exclusiveMinimum: 30000000
            maximum: 39000000
        - name: to
          in: path
          required: true
          description: GET /calc/path/:from/:to Parameter
          schema:
            type: number
            format: double
            exclusiveMinimum: 30000000
            maximum: 39000000
        - name: jumpDistance
          in: query
          required: true
          description: GET /calc/path/:from/:to Parameter
          schema:
            type: number
            format: double
            exclusiveMinimum: 0
            maximum: 500
            default: 0
        - name: optimize
          in: query
          required: false
          description: GET /calc/path/:from/:to Parameter
          schema:
            type: string
            enum:
              - fuel
              - distance
              - hops
            default: fuel
        - name: useSmartGates
          in: query
          required: false
          description: GET /calc/path/:from/:to Parameter
          schema:
            type: string
            default: ""
      responses:
        "200":
          description: GET /calc/path/:from/:to Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  path:
                    type: array
                    items:
                      oneOf:
                        - type: object
                          properties:
                            from:
                              type: number
                              format: double
                              minimum: -1.7976931348623157e+308
                              maximum: 1.7976931348623157e+308
                            to:
                              type: number
                              format: double
                              minimum: -1.7976931348623157e+308
                              maximum: 1.7976931348623157e+308
                            distance:
                              type: number
                              format: double
                              minimum: -1.7976931348623157e+308
                              maximum: 1.7976931348623157e+308
                            type:
                              type: string
                              enum:
                                - jump
                                - gate
                          required:
                            - from
                            - to
                            - distance
                            - type
                        - type: object
                          properties:
                            from:
                              type: number
                              format: double
                              minimum: -1.7976931348623157e+308
                              maximum: 1.7976931348623157e+308
                            to:
                              type: number
                              format: double
                              minimum: -1.7976931348623157e+308
                              maximum: 1.7976931348623157e+308
                            distance:
                              type: number
                              format: double
                              minimum: -1.7976931348623157e+308
                              maximum: 1.7976931348623157e+308
                            type:
                              type: string
                              const: smartgate
                            id:
                              type: string
                            owner:
                              type: object
                              properties:
                                address:
                                  type: string
                                id:
                                  type: string
                                name:
                                  type: string
                                corpId:
                                  type: number
                                  format: double
                                  minimum: -1.7976931348623157e+308
                                  maximum: 1.7976931348623157e+308
                              required:
                                - address
                                - id
                                - name
                                - corpId
                            name:
                              type: string
                            itemId:
                              type: string
                          required:
                            - from
                            - to
                            - distance
                            - type
                            - id
                            - itemId
                required:
                  - path
        "400":
          description: GET /calc/path/:from/:to Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /events:
    post:
      operationId: PostEvents
      requestBody:
        description: POST /events Request body
        content:
          application/json:
            schema:
              type: object
              properties:
                events:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      ts:
                        type: number
                        format: double
                        minimum: -1.7976931348623157e+308
                        maximum: 1.7976931348623157e+308
                    required:
                      - key
                      - ts
              required:
                - events
        required: true
      responses:
        "200":
          description: POST /events Positive response
          content:
            application/json:
              schema:
                type: object
        "400":
          description: POST /events Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers:
  - url: https://evedataco.re
